version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  run_unit_tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Set PYTHONPATH
          command: echo 'export PYTHONPATH=$PYTHONPATH:/home/circleci/project' >> $BASH_ENV
      - run:
          name: Install Dependencies and Run Unit Tests
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pytest --maxfail=5 --disable-warnings
      - save_cache:
          paths:
            - ~/.cache/pip
            - venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
workflows:
  version: 2
  build_and_test:
    jobs:
      - run_unit_tests
